context:
  version: "0.1.5"
  python_min: "3.10"  # they use X|Y type unions

package:
  name: batched
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/b/batched/batched-${{ version }}.tar.gz
    sha256: 58b8a41d3f8d4d39a0edba79c6238ed204938cfc2c8908224919d70af07c610d

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - batched
      pip_check: true

about:
  homepage: https://github.com/mixedbread-ai/batched
  summary: Batched is a flexible and efficient batch processing library implemented in Python. It supports asynchronous batch processing with dynamic batching and prioritization.
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - moritzwilksch
